### ISSUE TITLE
got WARN - etcd.watch.watcher: Close stream generating new etcd client

### ISSUE THREAD

**Issue by PythonEngineer007** [place-labs/crystal-etcd#10]
When I watch a key use watch_prefix, why I got the warn?
It looks like the etcd client close  then create a new client.
How can I set the watch timeout?

**Comment by PythonEngineer007** [comment]
Anyone can help me for the issue?  : )

**Comment by PythonEngineer007** [comment]
I found the condition "when timeout 1.minute" in  def forward_events.
It makes the warn and repeates to send the watch events to client.
I conmment the condition , it works no warn and no repeate the same events.

Why add the condition?

**Comment by caspiano** [comment]
Oh great! thanks for finding the issue! 
I believe the condition was there because TCP connections can be silently dropped, leaving the consumer waiting on IO off a dead socket.
Any suggestion that doesn't just recreate the client?

**Comment by caspiano** [comment]
It was a pretty brute way of doing a userland keep-alive. Should be fine now.
