### ISSUE TITLE
Investigate nilable fields

### ISSUE THREAD

**Issue by dukeraphaelng** [place-labs/crystal-etcd#13]
It is unclear why if a lease grant is not requested before a keep_alive request, the header and the ID of LeaseKeepAliveResponse is returned but not the TTL. This should be investigated so that we will have a comprehensive deserialisation model system

**Comment by dukeraphaelng** [comment]
etcd implements gRPC following proto3 which [follows](https://developers.google.com/protocol-buffers/docs/proto3#json):

```md
If a value is missing in the JSON-encoded data or if its value is null, it will be interpreted as the appropriate default value when parsed into a protocol buffer. If a field has the default value in the protocol buffer, it will be omitted in the JSON-encoded data by default to save space. An implementation may provide options to emit fields with default values in the JSON-encoded output.
```

The table for default values is as [follows](https://developers.google.com/protocol-buffers/docs/proto3#default)

**Comment by dukeraphaelng** [comment]
Please note, proto3 docs does not mention of the ability to declare custom defaults
https://developers.google.com/protocol-buffers/docs/proto3#simple

**Comment by dukeraphaelng** [comment]
@caspiano

**Comment by caspiano** [comment]
Good investigation @dukeraphaelng, seems resolved
