### ISSUE TITLE
how can I close a etcd client?

### ISSUE THREAD

**Issue by PythonEngineer007** [place-labs/crystal-etcd#17]
etcd = Etcd.from_env
When I call etcd.close, it still can use the etcd do all the operate.

so how can i close the client?

**Comment by caspiano** [comment]
`Etcd::Client#close` forwards the `close` to the underlying `HTTP::Client`

**Comment by caspiano** [comment]
An `Etcd::Watch::Watcher` has its own connection, this must be closed by calling `Etcd::Watch::Watcher#stop`
