### ISSUE TITLE
Error: unexpected token: @client

### ISSUE THREAD

**Issue by PythonEngineer007** [place-labs/crystal-etcd#8]
src/etcd/watch.cr:64
create_api: ->@client.spawn_api

How do I fix that?

**Comment by caspiano** [comment]
Sorry, could you provide more context?
At a minimum, could you provide your compiler version and the output of compiling your code with the `—error-trace` flag.
Some code to reproduce the issue would be ideal. 
I look forward to help solving your issue 🙂

**Comment by caspiano** [comment]
@PythonEngineer007 dfbbba64 creates a block proc that should resolve your issue. Please let me know if your issue is resolved.

**Comment by PythonEngineer007** [comment]
> @PythonEngineer007 [dfbbba6](https://github.com/place-labs/crystal-etcd/commit/dfbbba64d0ea2e6951b8b5e50459432499910ed4) creates a block proc that should resolve your issue. Please let me know if your issue is resolved.

yes, I can build it now, tks a lot

**Comment by PythonEngineer007** [comment]
After I change the crystal version to 0.35 the old code still works. May be you don't need to fix that.
