### ISSUE TITLE
Error: undefined constant ::Log

### ISSUE THREAD

**Issue by PythonEngineer007** [place-labs/crystal-etcd#9]
In etcd-test.cr:18:16
  18 | spawn { watcher.start }
Error: instantiating 'Etcd::Watch::Watcher#start()'

In /usr/share/crystal/app/lib/etcd/src/etcd/watch.cr:85:11
  85 | Log = ::Log.for(self)
Error: undefined constant ::Log

I build that at aarch64

**Comment by caspiano** [comment]
You are likely running an old crystal version.
This library requires a crystal version `~> 0.35`

**Comment by PythonEngineer007** [comment]
yes, it works.
